creation_rules:
- path_regex: data/deploy.yaml
  key_groups:
  - age:
    # -- @sportshead
    # v1.mbair.se
    - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
    # backup
    - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf

    # -- nix-ci
    - age15nd3vwj0rdx4258c2xkt953wa2d0mzf9vzgrq377s9yhhx30p9wsgk626r

